name: ESPHome Compile

on:
  pull_request:
    types: [closed]

permissions:
  contents: write  # Allow writing to repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Only run on PR merges

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Authenticated checkout for push
          ref: ${{ github.event.pull_request.merge_commit_sha }}  # Use merge commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config config/respeaker-satellite-factory-dashboard.yaml

      - name: Compile firmware
        run: |
          esphome compile config/respeaker-satellite-factory-dashboard.yaml || { echo "Compilation failed"; exit 1; }

      - name: Move and rename firmware
        run: |
          FIRMWARE_PATH=$(find config/.esphome/build -name firmware.bin)
          if [ -z "$FIRMWARE_PATH" ]; then
            echo "Error: Firmware file not found"
            find config/.esphome/build -type d
            exit 1
          fi
          echo "Found firmware at: $FIRMWARE_PATH"
          mkdir -p ota
          mv "$FIRMWARE_PATH" ota/idjmic-ota.bin

      - name: Verify firmware file
        run: ls -la ota/idjmic-ota.bin

      - name: Calculate MD5 and update manifest.json
        run: |
          # Calculate MD5
          MD5=$(md5sum ota/idjmic-ota.bin | cut -d' ' -f1)
          echo "MD5 checksum: $MD5"
          
          # Get version from PR source branch (e.g., 2025.4.1)
          VERSION=${{ github.event.pull_request.head.ref }}
          echo "Version: $VERSION"
          
          # Get PR title for summary
          SUMMARY=${{ github.event.pull_request.title }}
          echo "Summary: $SUMMARY"
          
          # Create or update manifest.json
          cat > ota/manifest.json << EOF
          {
            "name": "iDJMic Satellite",
            "version": "$VERSION",
            "home_assistant_domain": "esphome",
            "new_install_prompt_erase": false,
            "builds": [
              {
                "chipFamily": "ESP32-S3",
                "ota": {
                  "md5": "$MD5",
                  "path": "idjmic-ota.bin",
                  "release_url": "https://github.com/idjmic/Respeaker-Lite-ESPHome-integration",
                  "summary": "$SUMMARY"
                }
              }
            ]
          }
          EOF
          
          # Pretty-print JSON
          python -m json.tool ota/manifest.json > ota/manifest.json.tmp && mv ota/manifest.json.tmp ota/manifest.json
          
          echo "Updated ota/manifest.json:"
          cat ota/manifest.json

      - name: Commit and push OTA files to repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ota/idjmic-ota.bin ota/manifest.json
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update idjmic-ota.bin and manifest.json for version ${{ github.event.pull_request.head.ref }}"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
