name: ESPHome Compile

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config respeaker-satellite-factory-dashboard.yaml

      - name: Compile firmware
        run: esphome compile respeaker-satellite-factory-dashboard.yaml

      - name: Create ota directory
        run: mkdir -p ota

      - name: Find and copy firmware to ota folder
        run: |
          FIRMWARE_PATH=$(find .esphome/build/ -type f -name firmware.bin | head -n 1)
          echo "Found firmware at $FIRMWARE_PATH"
          cp "$FIRMWARE_PATH" ota/idjmic-ota.bin

      - name: Debug: List OTA contents
        run: |
          echo "Listing files in ota directory:"
          ls -lh ota || echo "No files found"

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: idjmic-ota
          path: ota/idjmic-ota.bin
