name: ESPHome Compile

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config config/respeaker-satellite-factory-dashboard.yaml

      - name: Compile firmware
        run: esphome compile config/respeaker-satellite-factory-dashboard.yaml || { echo "Compilation failed"; exit 1; }

      - name: Create ota directory if not exists
        run: mkdir -p ota

      - name: Move and rename firmware
        run: |
          FIRMWARE_PATH=".pioenvs/idjmic-satellite/firmware.bin"
          if [ ! -f "$FIRMWARE_PATH" ]; then
            echo "Error: Firmware file not found at $FIRMWARE_PATH"
            ls -la .pioenvs/idjmic-satellite/
            exit 1
          fi
          mv "$FIRMWARE_PATH" ota/idjmic-ota.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: idjmic-ota
          path: ota/idjmic-ota.bin
