name: ESPHome Compile

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure permission to push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config config/respeaker-satellite-factory-dashboard.yaml

      - name: Compile firmware
        run: |
          esphome compile config/respeaker-satellite-factory-dashboard.yaml || { echo "Compilation failed"; exit 1; }

      - name: Move and rename firmware
        run: |
          FIRMWARE_PATH=$(find config/.esphome/build -name firmware.bin)
          if [ -z "$FIRMWARE_PATH" ]; then
            echo "Error: Firmware file not found"
            find config/.esphome/build -type d
            exit 1
          fi
          echo "Found firmware at: $FIRMWARE_PATH"
          mkdir -p ota
          mv "$FIRMWARE_PATH" ota/idjmic-ota.bin

      - name: Verify firmware file
        run: ls -la ota/idjmic-ota.bin

      - name: Commit and push OTA file to repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ota/idjmic-ota.bin
          git commit -m "Update idjmic-ota.bin in ota/ folder" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
