name: ESPHome Compile

on:
  push:
    branches: [main, "20*"]  # Match branches like 2025.4.1
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Authenticated checkout for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config config/respeaker-satellite-factory-dashboard.yaml

      - name: Compile firmware
        run: |
          esphome compile config/respeaker-satellite-factory-dashboard.yaml || { echo "Compilation failed"; exit 1; }

      - name: Move and rename firmware
        run: |
          FIRMWARE_PATH=$(find config/.esphome/build -name firmware.bin)
          if [ -z "$FIRMWARE_PATH" ]; then
            echo "Error: Firmware file not found"
            find config/.esphome/build -type d
            exit 1
          fi
          echo "Found firmware at: $FIRMWARE_PATH"
          mkdir -p ota
          mv "$FIRMWARE_PATH" ota/idjmic-ota.bin

      - name: Verify firmware file
        run: ls -la ota/idjmic-ota.bin

      - name: Calculate MD5 and update firmware.json
        run: |
          # Calculate MD5
          MD5=$(md5sum ota/idjmic-ota.bin | cut -d' ' -f1)
          echo "MD5 checksum: $MD5"
          
          # Get version from branch name (e.g., refs/heads/2025.4.1 -> 2025.4.1)
          VERSION=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
          echo "Version: $VERSION"
          
          # Create or update firmware.json
          cat > ota/firmware.json << EOF
          {
            "name": "iDJMic Satellite",
            "version": "$VERSION",
            "home_assistant_domain": "esphome",
            "new_install_prompt_erase": false,
            "builds": [
              {
                "chipFamily": "ESP32-S3",
                "ota": {
                  "md5": "$MD5",
                  "path": "idjmic-ota.bin",
                  "release_url": "https://github.com/idjmic/Respeaker-Lite-ESPHome-integration",
                  "summary": "Amazing community update, Alarm functionality. Some improvements in media player stop handling. TTS URI replaced with event"
                }
              }
            ]
          }
          EOF
          
          # Pretty-print JSON for readability
          python -m json.tool ota/firmware.json > ota/firmware.json.tmp && mv ota/firmware.json.tmp ota/firmware.json
          
          echo "Updated ota/firmware.json:"
          cat ota/firmware.json

      - name: Commit and push OTA files to repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ota/idjmic-ota.bin ota/firmware.json
 
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update idjmic-ota.bin and firmware.json for version ${{ github.ref_name }}"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}